language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - composer install --dev --prefer-source
